# Generated by Django 4.1.6 on 2023-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
