# Generated by Django 4.1.6 on 2023-02-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_favorite_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
