# Generated by Django 4.1.6 on 2023-02-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='actvation_code',
            new_name='activation_code',
        ),
    ]
